# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.CharField(max_length=50)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=256)),
                ('span1', models.CharField(max_length=50)),
                ('span2', models.CharField(max_length=50)),
                ('span3', models.CharField(max_length=50)),
                ('span4', models.CharField(max_length=50)),
                ('span5', models.CharField(max_length=50)),
                ('span6', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_showgoods',
            },
        ),
    ]
